### PR TITLE
Typing fix

### PR DESCRIPTION
**Pull request by runnez**
Hi there! Thank you for great module, I like it :) 
I've added some missing types

### CODE REVIEW

**Comment by runnez** [comment]
There is some example https://github.com/nuxt-community/axios-module/blob/dev/types/index.d.ts

**Comment by microcipcip** [comment]
What is the purpose of this? Will this allow for type check when destructuring the $cookies lib from nuxt `app` object?

**Comment by runnez** [comment]
Yes! It allows getting $cookies typings in nuxt middleware.

**Comment by runnez** [comment]
image

**Comment by runnez** [comment]
This code works in my global.d.ts. But to be honest I could not check it - because of lerna

**Comment by microcipcip** [comment]
Ok, I'll test it locally this week and merge it if all is good, thanks for the PR :)

**Comment by microcipcip** [comment]
@runnez Apologies for the delay, I have merged your fix, however not having a typescript project set up I am unable to check it properly. 

Would you be able to download the latest version and let me know if everything is working well?

**Pull request merged**
