### PR TITLE
fix: added nodeCookie type for ICookie

### PR DESCRIPTION
**Pull request by stephenjason89**
Updated type definitions

### CODE REVIEW

**Comment by microcipcip** [comment]
That's awesome! Do you know why all lines are being considered changed?

**Comment by stephenjason89** [comment]
@microcipcip I'm not sure, but most probably because of the line breaks? I'm on mac. So might be because it's using LF and not CRLF?

**Comment by microcipcip** [comment]
I see, I may have to convert all files to that.

**Comment by stephenjason89** [comment]
@microcipcip maybe you can also use gitattributes to force convertion to CRLF to match the project?
I just keep mine in auto though 😅

**Comment by microcipcip** [comment]
I'll do that as well, good point!

**Pull request merged**
